### ISSUE TITLE
hello Odell, I improved this program and let me commit it

### ISSUE THREAD

**Issue by npumsy** [OdellDotson/Direct_Shooting_Simulation-_Single_and_Multiple_Shooting#1]
I wrote a readme.md file about how DSS and DMS work, provided 3 examples, including a time free problem, an rocket landing problem, and debugged your DMS function, now it works well. I find your repo useful for beginners and please make me a contributor, so I could access it and commit  them in your reposity @OdellDotson

**Comment by OdellDotson** [comment]
It is done, thank you for your interest.
